### ISSUE TITLE
set automatically coerce_shape for xarray_image

### ISSUE THREAD

**Issue by acocac** [intake/intake-xarray#104]
I have a local directory with GeoTIFF files with different shapes. I've explored the `coerce_shape` parameter to define manually a certain shape. I'm wondered if there's a workaround to coerce all images according to the largest shape in the directory instead of defining it manually. The following lines show how I define the catalog:

```
[...]
sources:
  test1:
    driver: xarray_image
    args:
      urlpath: '{{ CATALOG_DIR }}/data/*.tif'
      coerce_shape: [400,400]
[...]
```
