### ISSUE TITLE
AttributeError: 'NetCDFSource' object has no attribute 'pattern'

### ISSUE THREAD

**Issue by wachsylon** [intake/intake-xarray#142]
I think `self.pattern` needs to be changed into `self.path_as_pattern`:

https://github.com/intake/intake-xarray/blob/d0418f787181d638629b76c2982a9a215a3697be/intake_xarray/netcdf.py#L73

I run into the issue with a simple
```
sources:
  2D_const_0.25deg:
    description: 2D constant variables from IFS-AMIP
    driver: netcdf
    args:
      urlpath: "/work/bk1377/b382473/IFS_AMIP/prepIFS/OSTIA/gribscan/2D_const_0.25deg/*.grib"
      xarray_kwargs:
        engine: cfgrib
```
catalog.
