### ISSUE TITLE
How to template chunk specs?

### ISSUE THREAD

**Issue by willirath** [intake/intake-xarray#59]
I have a use case where I'd like to catalog NEMO data and chunk depth dims which are called differently (`deptht`, `depthu`, ...).

The following explains (I hope), what I want to achieve:
```yaml
[...]
sources:
  NEMO-Exp01:
    description: NEMO-Exp01
    driver: netcdf
    parameters:
      grid:
        description: grid
        allowed: ["t", "u", "v", "w"]
        default: "t"
        type: str
    args:
      urlpath: '/data/NEMO-Exp01/NEMO-Exp01_1m_20010101_20011231_grid_{{ grid.upper() }}.nc'
      chunks: {'depth{{ grid }}': 1, }
[...]
```

Is there a short way of doing this (without having 34 different entries that only differ in their grid)?
