### ISSUE TITLE
Is it possible to define default plots for xarrays/ xarray dataarrays?

### ISSUE THREAD

**Issue by cwerner** [intake/intake-xarray#84]
Hi.

I'd like to specify one or two default visualizations for an intake_xarray set. However, I cannot find any info how to specify:
- a z-dimension I need to select
- a datavariable 

Is this possible?

Currently, I use this:
```
    metadata:
      plots:
        a_plot_name:
          kind: 'image'
          x: 'lon'
          y: 'lat'
          rasterize: True
```
